# server:
#   port: 8082

# spring:
#   kafka:
#     consumer:
#       bootstrap-server: localhost:9092
#       group-id: group_id
#       auto-offset-reset: earliest
#       key-serializer: org.apache.kafka.common.serialization.StringDeserializer
#       value-serializer: org.apache.kafka.common.serialization.StringDeserializer